### ISSUE TITLE
How does this method compare with LightGlue?

### ISSUE THREAD

**Issue by luohongk** [verlab/accelerated_features#14]
SuperPoint+LightGlue is also a fast and lightweight feature extraction and matching solution, so I think this model can be compared with them.

**Comment by guipotje** [comment]
Hi @luohongk, thanks for bringing that up!

Firstly, XFeat should be significantly faster than SuperPoint alone, and it also offers a more compact descriptor. For instance, the SuperPoint descriptor dimension is 256, while XFeat produces a 64-dimension descriptor, which is four times smaller. In my local tests, SuperPoint barely runs at 3 FPS on my laptop CPU (in VGA resolution), whereas XFeat operates at over 25 FPS. Adding LightGlue further increases the computational requirements. For example, the original LightGlue repository indicates that it takes more than 100ms to match 1,024 (precomputed) descriptors on an i7 desktop CPU.

That being said, combining SuperPoint with LightGlue yields greater accuracy for challenging image pairs due to the robustness provided by learning the matching process through a transformer architecture. Please check our [supplementary](https://arxiv.org/pdf/2404.19174) material for a quantitative comparison with SP + LG.

**Comment by luohongk** [comment]
thank you

**Comment by guipotje** [comment]
Closing the issue as it appears to be clarified. If you need further clarifications, feel free to re-open it!
