### ISSUE TITLE
How does this method perform if training without Reliability Map?

### ISSUE THREAD

**Issue by weich37** [verlab/accelerated_features#15]
Hello. Thank you for your nice work and contribution of field.

I have some questions.

1. How does this method perform if training without Reliability Map?
2. Since the method detected keypoints with simple network(only 4 1*1 conv), did you validate some metric about keypoint detection, e.g. Repeatability?

I look forward to your reply and thank you for your excellent work!

**Comment by guipotje** [comment]
Hi @weich37, thank you for your interest in our work!

Q1: For semi-dense matching, you can match the full (dense) descriptor map without filtering based on reliability (no need to train with a reliability map). This should provide the densest matching, but the inlier ratio (#correct/#total) may decrease, and the matching cost will increase.

Q2: We did not check keypoint repeatability because it does not always correlate well with downstream task performance. Instead, we directly evaluated the keypoints/descriptors on downstream tasks such as camera pose, homography estimation, and visual localization.

**Comment by weich37** [comment]
Thank you
